import tkinter as tk
from tkinter import font
import keyboard
from time import sleep
import pyautogui as pya
import threading as th
import random
import base64
import os

pya.PAUSE=0

class Main(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self.geometry("512x384")
        self.minsize(512,384)
        self.maxsize(512,384)
        self.title("Autoclicker v1.0")
        self.iconMagic()

        self.bold=font.Font(family="Javanese Text",size="12",weight="bold")

        container=tk.Frame(self)
        container.pack(side="top",fill="both",expand=True)
        container.grid_rowconfigure(0,weight=1)
        container.grid_columnconfigure(0,weight=1)

        self.frames = {}
        for F in (MainPage,Credits):
            page_name = F.__name__
            frame=F(parent=container,cont=self)
            self.frames[page_name]=frame

            frame.grid(row=0,column=0,sticky="nsew")

        self.show_frame("MainPage")

    def show_frame(self,page_name):
        frame = self.frames[page_name]
        frame.tkraise()

    def iconMagic(self):    #XDDDDDDDDDDDDDDDDDDDD, what great programming
        icondata = base64.b64decode(iconbase64)
        tempFile = "icon.ico"
        iconfile = open(tempFile,"wb")
        iconfile.write(icondata)
        iconfile.close()
        self.iconbitmap(tempFile)
        os.remove(tempFile)
        #Thank you Saúl Pilatowsky-Cameo - https://stackoverflow.com/a/10165432

class MainPage(tk.Frame):
    def __init__(self, parent, cont):
        tk.Frame.__init__(self,parent)
        self.clickThread=th.Thread(target=self.clicks)
        self.clicking = False
        self.clickSpeed=1000
        self.clickVary=0
        self.cont = cont

        #Clicking -indicator
        self.ClickingOnLabel = tk.Label(self,text="OFF",font=cont.bold,bg="red")
        self.ClickingOnLabel.place(relx=0.5,rely=0.05,anchor="center",height="25")
        ShortcutLabel = tk.Label(self,text="CTRL + ALT + C")
        ShortcutLabel.place(relx=0.5,rely=0.1,anchor="center")

        #ClickSpeed text & entry
        ClickSpeedLabel = tk.Label(self,text="Click Speed",font=cont.bold)
        ClickSpeedLabel.place(relx=0.5,rely=0.2,anchor="center")
        MeasurementLabel = tk.Label(self,text="(ms)")
        MeasurementLabel.place(relx=0.5,rely=0.235,anchor="center")
        self.ClickSpeedEntry = tk.Entry(self,justify="center")
        self.ClickSpeedEntry.place(relx=0.5,rely=0.3,anchor="center")
        self.ClickSpeedEntry.insert(0,str(self.clickSpeed))

        #ClickSpeedVary text & entry
        ClickVaryLabel = tk.Label(self,text="Click Vary",font=cont.bold)
        ClickVaryLabel.place(relx=0.8,rely=0.2,anchor="center")
        MeasurementLabel = tk.Label(self,text="(ms)")
        MeasurementLabel.place(relx=0.8,rely=0.235,anchor="center")
        self.ClickVaryEntry = tk.Entry(self,justify="center")
        self.ClickVaryEntry.place(relx=0.8,rely=0.3,anchor="center",width="75")
        self.ClickVaryEntry.insert(0,str(self.clickVary))

        keyboard.add_hotkey('ctrl+alt+c', self.startClick)

    def startClick(self):
        self.clickSpeed=int(self.ClickSpeedEntry.get())
        self.clickVary=int(self.ClickVaryEntry.get())
        self.clicking = not self.clicking
        if self.clicking:
            self.ClickingOnLabel.config(text="ON",bg="lightgreen")
            try:
                self.clickThread.start()
            except RuntimeError:
                self.clickThread=th.Thread(target=self.clicks)
                self.clickThread.start()
        else:
            self.ClickingOnLabel.config(text="OFF",bg="red")

    def clicks(self):
        while True:
            if not self.clicking:
                break
            pya.click()
            sleep((self.clickSpeed/1000)+(random.randint(0,self.clickVary)/1000))
            if self.clickSpeed != int(self.ClickSpeedEntry.get()):
                self.startClick()
                break
        

class Credits(tk.Frame):
    def __init__(self,parent,cont):
        tk.Frame.__init__(self,parent)
        self.cont=cont
        Title=tk.Label(self,text="Credits")
        Title.grid(column=0,row=0)
        button = tk.Button(self,text="Leave credits",command=lambda: cont.show_frame("StartPage"))
        button.grid(column=0,row=1,sticky="W")

#Too stupid and stubborn to spend an hour learning pyinstaller's proper use so...
iconbase64 = """AAABAAYAMDAAAAEAIACoJQAAZgAAADAwAAABAAgAqA4AAA4mAAAgIAAAAQAgAKgQAAC2NAAAICAA
AAEACACoCAAAXkUAABAQAAABACAAaAQAAAZOAAAQEAAAAQAIAGgFAABuUgAAKAAAADAAAABgAAAA
AQAgAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA//z8EVP44Elv+MCpb/zNAWv8yYFr/MmZc/jFIW/4tHAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAVf8qBlr/NCJZ/jNKWv4xdlv+MZRb/jKoW/8xqlv+MaRb/jGWWv4ynlv+MZZa
/jJuXP4xSFv+LRwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/W/8y/1v+Mv5b/zHw
Wv4x2Fr+MtZb/zLAW/4yxlr+Mrxb/jGWWv4yblz+MUhb/i0cAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
//////8AAAD/AAAA/1v/Mv9b/zL/W/8y/1v/Mv9a/jHsWv4x8lr+MuRa/jK8W/4xllr+Mm5c/jFI
W/4tHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////AAAA/wAAAP9b/zL/W/8y/1v/Mv9b/zL/W/8y
/1v/Mv9a/jLkWv4yvFv+MZZa/jJuXP4xSFv+LRwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////wAA
AP8AAAD/W/8y/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/Wv4y5Fr+Mrxb/jGWWv4yblz+MUhb/i0cAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA//////////////////////8AAAD/AAAA/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/W/8y/1r+
MuRa/jK8W/4xllr+Mm5c/jFIW/4tHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////AAAA/wAAAP9b
/zL/W/8y/1v/Mv9b/zL/W/8y/1v/Mv9a/jLkWv4yvFv+MZZa/jJuXP4xSFv+LRwAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////
/////////////////////wAAAP8AAAD/W/8y/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/Wv4y5Fr+Mrxb
/jGWWv4yblz+MUhb/i0cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA//////////////////////////////////////8AAAD/AAAA/1v/Mv9b/zL/
W/8y/1v/Mv9b/zL/W/8y/1r+MuRa/jK8W/4xllr+Mm5c/jFIW/4tHAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////
////////////AAAA/wAAAP9b/zL/W/8y/1v/Mv9b/zL/W/8y/1v/Mv9a/jLkW/4xvlv+MaRa/jKS
W/4xjFv+MYxb/jGMW/4xjFv+MYxb/jGMW/4xjFv+MYxb/jGMW/4xjFv+MYxb/jGMW/4xjFv+MYxb
/jGMW/4xjFv+MYxb/jGMW/8yiFr+MXxa/zJmXP4xSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////
/////////////////////////////////////////////wAAAP8AAAD/W/8y/1v/Mv9b/zL/W/8y
/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/
W/8y/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/W/4x4lv+MrBb/zGAW/4xTgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////////////////////
//8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/
W/4x4lv+MrBb/zGAW/4xTgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////AAAA
/1v/Mv9b/zL/W/8y/1v/Mv9b/zL/Wv4y1lv+MZpa/zJgWv80IgAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAA////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////8AAAD/AAAA/1v/Mv9b/zL/W/8y/1v/Mv9a/jLWW/4xmlr/MmBa/zQiAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////wAAAP8AAAD/W/8y/1v/Mv9b/zL/W/8y/1r+
MtZb/jGaWv8yYFr/NCIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////AAAA/wAAAP9b
/zL/W/8y/1v/Mv9b/zL/Wv4y1lv+MZpa/zJgWv80IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////8AAAD/AAAA/1v/Mv9b/zL/W/8y/1v/Mv9a/jLWW/4xmlr/MmBa/zQiAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////wAAAP8AAAD/W/8y/1v/Mv9b/zL/W/8y/1r+MtZb/jGa
Wv8yYFr/NCIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////AAAA/wAAAP9b/zL/W/8y
/1v/Mv9b/zL/Wv4y1lv+MZpa/zJgWv80IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//8AAAD/AAAA/1v/Mv9b/zL/W/8y/1v/Mv9a/jLWW/4xmlr/MmBa/zQiAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////wAAAP8AAAD/W/8y/1v/Mv9b/zL/W/8y/1r+MtZb/jGaWv8yYFr/
NCIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////AAAA/wAAAP9b/zL/W/8y/1v/Mv9b
/zL/Wv4y1lv+MZpa/zJgWv80IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////8AAAD/
AAAA/1v/Mv9b/zL/W/8y/1v/Mv9a/jLWW/4xmlr/MmBa/zQiAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////wAAAP8AAAD/W/8y/1v/Mv9b/zL/W/8y/1r+MtZb/jGaWv8yYFr/NCIAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA////////////////////////////////////////////////////////////////////
////////////////////////////////////////AAAA/wAAAP9b/zL/W/8y/1v/Mv9b/zL/Wv4y
1lv+MZpa/zJgWv80IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////////
//////////////////////////////////////////////////////////////8AAAD/AAAA/1v/
Mv9b/zL/W/8y/1v/Mv9a/jLWW/4xmlr/MmBa/zQiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////
////////////////////////////////////////////////////////////////////////////
/////////wAAAP8AAAD/W/8y/1v/Mv9b/zL/W/8y/1r+MtZb/jGaWv8yYFr/NCIAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA////////////////////////////////////////////////////////////
////////////////////////////////AAAA/wAAAP9b/zL/W/8y/1v/Mv9b/zL/Wv4y1lv+MZpa
/zJgWv80IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////
//////////////////////////////////////////////////////8AAAD/AAAA/1v/Mv9b/zL/
W/8y/1v/Mv9a/jLWW/4xmlr/MmBa/zQiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////
////////////////////////////////////////////////////////////////////////////
/wAAAP8AAAD/W/8y/1v/Mv9b/zL/W/8y/1r+MtZb/jGaWv8yYFr/NCIAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////////////////////
////////////////////////AAAA/wAAAP9b/zL/W/8y/1v/Mv9b/zL/Wv4y1lv+MZpa/zJgWv80
IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////
//////////////////////////////////////////////8AAAD/AAAA/1v/Mv9b/zL/W/8y/1v/
Mv9a/jLWW/4xmlr/MmBa/zQiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAA/////////////////////////////////////////////////////////////////wAAAP8A
AAD/W/8y/1v/Mv9b/zL/W/8y/1r+MtZb/jGaWv8yYFr/NCIAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////////////
////////////////AAAA/wAAAP9b/zL/W/8y/1v/Mv9b/zL/Wv4y1lv+MZpa/zJgWv80IgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////
//////////////////////////////////////8AAAD/AAAA/1v/Mv9b/zL/W/8y/1v/Mv9a/jLW
W/4xmlr/MmBa/zQiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAA/////////////////////////////////////////////////wAAAP8AAAD/W/8y
/1v/Mv9b/zL/W/8y/1r+MtZb/jGaWv8yYFr/NCIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////////
////////AAAA/wAAAP9b/zL/W/8y/1v/Mv9b/zL/Wv4y1lv+MZpa/zJgWv80IgAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////
//////////////////////////////8AAAD/AAAA/1v/Mv9b/zL/W/8y/1v/Mv9a/jLWW/4xmlr/
MmBa/zQiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA/////////////////////////////////wAAAP8AAAD/W/8y/1v/Mv9b
/zL/W/8y/1r+MtZb/jGaWv8yYFr/NCIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////
AAAA/wAAAP9b/zL/W/8y/1v/Mv9b/zL/Wv4y1lv+MZpa/zJgWv80IgAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
//////////////////////8AAAD/AAAA/1v/Mv9b/zL/W/8y/1v/Mv9a/jLWW/4xmlr/MmBa/zQi
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////wAAAP8AAAD/W/8y/1v/Mv9b/zL/W/4y
+Fr+MtZb/jGaWv8yYFr/NCIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////AAAA/wAA
AP9b/zL/W/8y/1r+MfJb/jLGW/4xuFr+Mphc/jBeWv80IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA//////8AAAD/AAAA/1v/Mv9b/jL4W/4xuFv+MYZb/jJWXf4xNF//NRhV/yoGAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/W/4xpFv+MXJd/jE0VP44EgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAP///////wAA/4D/////AAD4AH////8AAPgAP////wAA+AAf////AAD4AA////8A
APgAB////wAA+AAD////AAD4AAH///8AAPgAAP///wAA+AAAAAAHAAD4AAAAAAEAAPgAAAAAAQAA
+AAAAAADAAD4AAAAAAcAAPgAAAAADwAA+AAAAAAfAAD4AAAAAD8AAPgAAAAAfwAA+AAAAAD/AAD4
AAAAAf8AAPgAAAAD/wAA+AAAAAf/AAD4AAAAD/8AAPgAAAAf/wAA+AAAAD//AAD4AAAAf/8AAPgA
AAD//wAA+AAAAf//AAD4AAAD//8AAPgAAAf//wAA+AAAD///AAD4AAAf//8AAPgAAD///wAA+AAA
f///AAD4AAD///8AAPgAAf///wAA+AAD////AAD4AAf///8AAPgAD////wAA+AAf////AAD4AD//
//8AAPgAf////wAA+AD/////AAD4B/////8AAPh//////wAA////////AAD///////8AACgAAAAw
AAAAYAAAAAEACAAAAAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAAD/W/8y//////8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAAAAAQEAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAAAAAQEAAgAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAA
AQEAAgIAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAAAB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgAAAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgIAAAEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAAAAAQEAAgICAgICAgAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AAAAAQEAAgICAgICAgIAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgIC
AgICAgICAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgICAgICAgIC
AgICAgICAgICAgIAAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC
AgAAAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAAABAQEBAQEB
AQEBAAAAAQEAAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAEBAQEBAQEBAQEBAAAAAQEA
AgICAgICAgICAgICAgICAgICAgICAgICAgICAgAAAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgIC
AgICAgICAgICAgICAgICAgICAAABAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgICAgIC
AgICAgICAgIAAAEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgICAgICAgICAgICAgAA
AQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgICAgICAgICAgICAAABAQEBAQEBAQEB
AQEBAQEBAAAAAQEAAgICAgICAgICAgICAgICAgICAgICAgIAAAEBAQEBAQEBAQEBAQEBAQEBAAAA
AQEAAgICAgICAgICAgICAgICAgICAgICAgAAAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgIC
AgICAgICAgICAgICAgICAAABAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgIC
AgICAgIAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgICAgICAgAAAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgICAgICAAABAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgICAgIAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AAAAAQEAAgICAgICAgICAgICAgICAgAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgIC
AgICAgICAgICAgICAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgIC
AgIAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAgAAAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgICAAABAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgICAgIAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAAAAAQEAAgICAgICAgICAgAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEA
AgICAgICAgICAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgIA
AAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAgAAAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgICAAABAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAAAAAQEAAgICAgIAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAAAAAQEAAgICAgAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAA
AQEAAgICAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgIAAAEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAgAAAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
////////AAD/gP////8AAPgAf////wAA+AA/////AAD4AB////8AAPgAD////wAA+AAH////AAD4
AAP///8AAPgAAf///wAA+AAA////AAD4AAAAAAcAAPgAAAAAAQAA+AAAAAABAAD4AAAAAAMAAPgA
AAAABwAA+AAAAAAPAAD4AAAAAB8AAPgAAAAAPwAA+AAAAAB/AAD4AAAAAP8AAPgAAAAB/wAA+AAA
AAP/AAD4AAAAB/8AAPgAAAAP/wAA+AAAAB//AAD4AAAAP/8AAPgAAAB//wAA+AAAAP//AAD4AAAB
//8AAPgAAAP//wAA+AAAB///AAD4AAAP//8AAPgAAB///wAA+AAAP///AAD4AAB///8AAPgAAP//
/wAA+AAB////AAD4AAP///8AAPgAB////wAA+AAP////AAD4AB////8AAPgAP////wAA+AB/////
AAD4AP////8AAPgH/////wAA+H//////AAD///////8AAP///////wAAKAAAACAAAABAAAAAAQAg
AAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAFc/i4LXv4vG1v+NCdb/jA1
Wv4yTFn+Mmlb/jJqW/4yMmb/MwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAkQUN
AspHxibaW/4x4lv+MtFa/jLFWv4xulr+Mala/jJuWv8yM2b/MwUAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAC/z8/P/xAQEP9Kzyn/W/8y/1v+Mfta/jL0W/4x4lr+Mala/jJuW/4yMmb/MwUA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL//////z8/P/wYQA/9Kzyn/W/8y/1v/Mv9a/jL9W/4x
4lr+Mala/jJuWv8yM2b/MwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv///////////z8/P/xAQEP9K
zyn/W/8y/1v/Mv9b/zL/W/4x4lr+Mala/jJuW/4yMmb/MwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/////
////////////z8/P/wYQA/9Kzyn/W/8y/1v/Mv9a/jL9W/4x4lr+Mala/jJuWv8yM2b/MwUAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAL//////////////////////z8/P/xAQEP9Kzyn/W/8y/1v/Mv9b/zL/W/4x4lv/
Mapa/jJzWv4yQVf+MiNX/jIjV/4yI1f+MiNX/jIjV/4yI1f+MiNX/jIjV/4yI1f+MiNX/jIjWv80
Il3/Mx5Z/zMUAAAAAAAAAAAAAAAAAAAAv///////////////////////////z8/P/wYQA/9Kzyn/
W/8y/1v/Mv9a/jL9Wv4x8Vr+Meda/jLjW/4x4lv+MeJb/jHiW/4x4lv+MeJb/jHiW/4x4lv+MeJb
/jHiW/4x4lv+MeJb/jLRW/4xmVn+MVgAAAAAAAAAAAAAAAAAAAC/////////////////////////
////////z8/P/0BAQP9AQED/QEBA/0BAQP9AQED/QEBA/0BAQP9AQED/QEBA/0BAQP9AQED/QEBA
/0BAQP9AQED/EBAQ/1v/Mv9b/zL/W/8y/1r+Meda/jKeXP8zUAAAAAAAAAAAAAAAAAAAAL//////
////////////////////////////////////////////////////////////////////////////
/////////////////////////8/Pz/8QEBD/W/8y/1v/Mv9a/jH3Wv4yt1v+Ml9d/jUTAAAAAAAA
AAAAAAAAAAAAv///////////////////////////////////////////////////////////////
///////////////////////////////////////Pz8//BhAD/0rPKf9b/zL/Wv4x91v+Mbhb/jJf
Xf41EwAAAAAAAAAAAAAAAAAAAAAAAAC/////////////////////////////////////////////
////////////////////////////////////////////////////z8/P/xAQEP9Kzyn/W/8y/1r+
Mfda/jK3W/4yX13+NRMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL//////////////////////////
/////////////////////////////////////////////////////////////////8/Pz/8GEAP/
Ss8p/1v/Mv9a/jH3W/4xuFv+Ml9d/jUTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv///////
////////////////////////////////////////////////////////////////////////////
///Pz8//EBAQ/0rPKf9b/zL/Wv4x91r+Mrdb/jJfXf41EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAC/////////////////////////////////////////////////////////////////
////////////////z8/P/wYQA/9Kzyn/W/8y/1r+Mfdb/jG4W/4yX13+NRMAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAL//////////////////////////////////////////////
/////////////////////////////8/Pz/8QEBD/Ss8p/1v/Mv9a/jH3Wv4yt1v+Ml9d/jUTAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv///////////////////////////
///////////////////////////////////////////Pz8//BhAD/0rPKf9b/zL/Wv4x91v+Mbhb
/jJfXf41EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/////////
////////////////////////////////////////////////////////z8/P/xAQEP9Kzyn/W/8y
/1r+Mfda/jK3W/4yX13+NRMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAL///////////////////////////////////////////////////////////8/Pz/8G
EAP/Ss8p/1v/Mv9a/jH3W/4xuFv+Ml9d/jUTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAv///////////////////////////////////////////////
///////Pz8//EBAQ/0rPKf9b/zL/Wv4x91r+Mrdb/jJfXf41EwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/////////////////////////////
////////////////////z8/P/wYQA/9Kzyn/W/8y/1r+Mfdb/jG4W/4yX13+NRMAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL//////////
/////////////////////////////////8/Pz/8QEBD/Ss8p/1v/Mv9a/jH3Wv4yt1v+Ml9d/jUT
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAv//////////////////////////////////////Pz8//BhAD/0rPKf9b/zL/Wv4x91v+
Mbhb/jJfXf41EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAC/////////////////////////////////z8/P/xAQEP9Kzyn/
W/8y/1r+Mfda/jK3W/4yX13+NRMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL///////////////////////////8/P
z/8GEAP/Ss8p/1v/Mv9a/jH3W/4xuFv+Ml9d/jUTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv///////////
///////////Pz8//EBAQ/0rPKf9b/zL/Wv4x91r+Mrdb/jJfXf41EwAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAC/////////////////z8/P/wYQA/9Kzyn/W/8y/1r+Mfdb/jG4W/4yX13+NRMAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAL///////////8/Pz/8QEBD/Ss8p/1v/Mv9a/jH3Wv4yt1v+Ml9d
/jUTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv//////Pz8//BhAD/0rPKf9b/jL5W/4y
6lv+Mbhb/jJfXf41EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/z8/P/xAQEP9K
zin+Wv4y1lr+MZVb/jFcWP40MWL+Og0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAI8AAAC/PKcgjFn+M0pZ/zMUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD/////4B///+AP///gB///4AP//+AB///gAP//4AAAAeAAAAHgAAAD
4AAAB+AAAA/gAAAf4AAAP+AAAH/gAAD/4AAB/+AAA//gAAf/4AAP/+AAH//gAD//4AB//+AA///g
Af//4AP//+AH///gD///4B///+B////j/////////ygAAAAgAAAAQAAAAAEACAAAAAAAAAgAAAAA
AAAAAAAAAAAAAAAAAAAKHAb/HBwc/1VVVf9Hxif/W/8y/8bGxv//////AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAABAMEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDBAQEBAQE
BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAQMEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYF
AAMEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAABgYFAQMEBAQEBAQEBAAAAAAAAAAAAAAAAAAA
AAAAAAAGBgYFAAMEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAYGBgYFAQMEBAQEBAQEBAQEBAQE
BAQEBAQEBAQAAAAABgYGBgYFAAMEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAGBgYGBgYFAgICAgIC
AgICAgICAgIBBAQEBAQEAAAAAAYGBgYGBgYGBgYGBgYGBgYGBgYGBQEEBAQEBAQAAAAABgYGBgYG
BgYGBgYGBgYGBgYGBgUAAwQEBAQEAAAAAAAGBgYGBgYGBgYGBgYGBgYGBgYFAQMEBAQEBAAAAAAA
AAYGBgYGBgYGBgYGBgYGBgYGBQADBAQEBAQAAAAAAAAABgYGBgYGBgYGBgYGBgYGBgUBAwQEBAQE
AAAAAAAAAAAGBgYGBgYGBgYGBgYGBgYFAAMEBAQEBAAAAAAAAAAAAAYGBgYGBgYGBgYGBgYGBQED
BAQEBAQAAAAAAAAAAAAABgYGBgYGBgYGBgYGBgUAAwQEBAQEAAAAAAAAAAAAAAAGBgYGBgYGBgYG
BgYFAQMEBAQEBAAAAAAAAAAAAAAAAAYGBgYGBgYGBgYGBQADBAQEBAQAAAAAAAAAAAAAAAAABgYG
BgYGBgYGBgUBAwQEBAQEAAAAAAAAAAAAAAAAAAAGBgYGBgYGBgYFAAMEBAQEBAAAAAAAAAAAAAAA
AAAAAAYGBgYGBgYGBQEDBAQEBAQAAAAAAAAAAAAAAAAAAAAABgYGBgYGBgUAAwQEBAQEAAAAAAAA
AAAAAAAAAAAAAAAGBgYGBgYFAQMEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAYGBgYGBQADBAQEBAQA
AAAAAAAAAAAAAAAAAAAAAAAABgYGBgUBAwQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAGBgYFAAME
BAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGBQADBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
BgUAAwQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAMEBAQEBAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAACBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAP/////gH///4A///+AH///gA///4AH//+AA///gAAAB4AAAAeAAAAPgAAAH4AAA
D+AAAB/gAAA/4AAAf+AAAP/gAAH/4AAD/+AAB//gAA//4AAf/+AAP//gAH//4AD//+AB///gA///
4Af//+AP///gH///4H///+P/////////KAAAABAAAAAgAAAAAQAgAAAAAAAACAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAWf4zSlv+Mqhb/jGWWv4ybgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////9b/zL/W/8y/1r+MuRa/jJuAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////1v/Mv9b/zL/Wv4y5Fr+Mm4AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////W/8y/1v/Mv9a
/jLkWv4yklv+MYxb/jGMW/4xjFv+MYxb/jGMW/4xjFr/MmYAAAAAAAAAAP//////////////////
////////////////////////////////////////W/8y/1v/Mv9a/zJgAAAAAAAAAAD/////////
////////////////////////////////////////////W/8y/1v/Mv9a/zJgAAAAAAAAAAAAAAAA
////////////////////////////////////////////////W/8y/1v/Mv9a/zJgAAAAAAAAAAAA
AAAAAAAAAP//////////////////////////////////////////W/8y/1v/Mv9a/zJgAAAAAAAA
AAAAAAAAAAAAAAAAAAD/////////////////////////////////////W/8y/1v/Mv9a/zJgAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////////////W/8y/1v/Mv9a/zJg
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////////////////W/8y/1v/Mv9a
/zJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////W/8y/1v/
Mv9a/zJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////W/8y
/1v/Mv9a/zJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////
W/8y/1v/Mv9a/zJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/
////W/8y/1v+MsZc/jBeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAADn/wAAw/8AAMH/AADAAQAAwAEAAMADAADABwAAwA8AAMAfAADAPwAAwH8AAMD/AADB/wAA
w/8AAMf/AAD//wAAKAAAABAAAAAgAAAAAQAIAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAFVVVf89
qiH/W/8y/6qqqv/Gxsb//////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAACAgIC
AAAAAAAAAAAAAAADAQICAgIAAAAAAAAAAAAABAMBAgICAgAAAAAAAAAAAAQFAwECAgICAgICAgIC
AAAEBQUEAwMDAwMDAAICAgAABAUFBQUFBQUFAwECAgEAAAQFBQUFBQUFAwECAgEAAAAEBQUFBQUF
AwECAgEAAAAABAUFBQUFAwECAgEAAAAAAAQFBQUFAwECAgEAAAAAAAAEBQUFAwECAgEAAAAAAAAA
BAUFAwECAgEAAAAAAAAAAAQFAwECAgEAAAAAAAAAAAAEAwECAgEAAAAAAAAAAAAAAAEBAQEAAAAA
AAAAAAAAAAACAAAAAAAAAAAAAAAA5/8AAMP/AADB/wAAwAEAAMABAADAAwAAwAcAAMAPAADAHwAA
wD8AAMB/AADA/wAAwf8AAMP/AADH/wAA//8AAA=="""
#I will infact NOT be getting a job in compsci with this.

if __name__=="__main__":
    app=Main()
    app.mainloop()
